import { Category, Post, User, Collection, Comment, AppNotification } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-all',
    slug: 'all',
    name: 'All Inspiration',
    description: 'Explore visuals across disciplines and styles.',
    iconName: 'Sparkles',
    postCount: 384,
  },
  {
    id: 'cat-graphic-design',
    slug: 'graphic-design',
    name: 'Graphic Design',
    description: 'Editorial layouts, visual systems, Swiss typography and print experiments.',
    iconName: 'LayoutGrid',
    coverImageUrl: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?q=80&w=800&auto=format&fit=crop',
    postCount: 142,
  },
  {
    id: 'cat-posters',
    slug: 'posters',
    name: 'Posters',
    description: 'Brutalist, typographic, risograph, and experimental exhibition posters.',
    iconName: 'FileText',
    coverImageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    postCount: 98,
  },
  {
    id: 'cat-branding',
    slug: 'branding',
    name: 'Branding',
    description: 'Holistic brand identities, stationery suites, guidelines, and visual languages.',
    iconName: 'Layers',
    coverImageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=800&auto=format&fit=crop',
    postCount: 116,
  },
  {
    id: 'cat-logos',
    slug: 'logos',
    name: 'Logos',
    description: 'Monograms, dynamic marks, geometric emblems, and minimalist logotypes.',
    iconName: 'Award',
    coverImageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&auto=format&fit=crop',
    postCount: 84,
  },
  {
    id: 'cat-ui-ux',
    slug: 'ui-ux',
    name: 'UI/UX',
    description: 'Component libraries, design tokens, micro-interactions, and design systems.',
    iconName: 'Component',
    coverImageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=800&auto=format&fit=crop',
    postCount: 175,
  },
  {
    id: 'cat-website-design',
    slug: 'website-design',
    name: 'Website Design',
    description: 'Interactive landing pages, art-directed portfolios, and editorial web experiences.',
    iconName: 'Globe',
    coverImageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?q=80&w=800&auto=format&fit=crop',
    postCount: 153,
  },
  {
    id: 'cat-mobile-app-design',
    slug: 'mobile-app-design',
    name: 'Mobile App Design',
    description: 'iOS and Android interfaces, fluid gestures, clean widget architecture.',
    iconName: 'Smartphone',
    coverImageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
    postCount: 128,
  },
  {
    id: 'cat-packaging',
    slug: 'packaging',
    name: 'Packaging',
    description: 'Sustainable product packaging, tactile finishes, embossed labels, and bottles.',
    iconName: 'Package',
    coverImageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop',
    postCount: 67,
  },
  {
    id: 'cat-illustration',
    slug: 'illustration',
    name: 'Illustration',
    description: 'Vector artwork, digital paintings, line art, gouache textures, and editorial scenes.',
    iconName: 'PenTool',
    coverImageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    postCount: 194,
  },
  {
    id: 'cat-photography',
    slug: 'photography',
    name: 'Photography',
    description: 'Architectural minimalism, editorial fashion, analog 35mm grain, and light studies.',
    iconName: 'Camera',
    coverImageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop',
    postCount: 220,
  },
  {
    id: 'cat-3d',
    slug: '3d',
    name: '3D',
    description: 'Abstract materials, procedural geometry, octane renders, and kinetic typography in 3D.',
    iconName: 'Box',
    coverImageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=800&auto=format&fit=crop',
    postCount: 160,
  },
  {
    id: 'cat-ai-art',
    slug: 'ai-art',
    name: 'AI Art',
    description: 'Latent space exploration, surreal concept renders, and generative textures.',
    iconName: 'Wand2',
    coverImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    postCount: 112,
  },
  {
    id: 'cat-social-media-design',
    slug: 'social-media-design',
    name: 'Social Media Design',
    description: 'Carousel storyboards, typographic grids, promotional kits, and motion snippets.',
    iconName: 'Share2',
    coverImageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop',
    postCount: 89,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-elena',
    username: 'elenavance',
    displayName: 'Elena Vance',
    email: 'elena@studionord.design',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    bio: 'Visual director & Swiss typography enthusiast. Exploring brutalist layout systems and tactile editorial packaging.',
    websiteUrl: 'https://elenavance.design',
    location: 'Zurich, Switzerland',
    followersCount: 14200,
    followingCount: 340,
    postsCount: 28,
    collectionsCount: 6,
    profileViews: 14200,
    createdAt: '2025-01-15T09:00:00Z',
  },
  {
    id: 'user-mono',
    username: 'studiomono',
    displayName: 'Studio Mono',
    email: 'hello@studiomono.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop',
    bio: 'Independent creative studio focusing on high-craft digital products, generative art, and spatial UI experiences.',
    websiteUrl: 'https://studiomono.io',
    location: 'Berlin, Germany',
    followersCount: 29800,
    followingCount: 120,
    postsCount: 42,
    collectionsCount: 12,
    profileViews: 28400,
    createdAt: '2024-11-20T10:30:00Z',
  },
  {
    id: 'user-kaelen',
    username: 'kaelen',
    displayName: 'Kaelen Rhee',
    email: 'kaelen@rhee.studio',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    bio: '3D Designer & Art Director. Crafting procedural glass shaders, chromatic lighting, and tactile product renders.',
    websiteUrl: 'https://kaelen.art',
    location: 'Seoul, South Korea',
    followersCount: 8900,
    followingCount: 215,
    postsCount: 19,
    collectionsCount: 4,
    profileViews: 9600,
    createdAt: '2025-03-02T14:15:00Z',
  },
  {
    id: 'user-sofia',
    username: 'sofiarostova',
    displayName: 'Sofia Rostova',
    email: 'sofia@rostova.com',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=300&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    bio: 'Architectural photographer and brand strategist. Documenting brutalist concrete structures and warm shadows.',
    websiteUrl: 'https://sofiarostova.photo',
    location: 'Stockholm, Sweden',
    followersCount: 16500,
    followingCount: 480,
    postsCount: 35,
    collectionsCount: 9,
    profileViews: 17800,
    createdAt: '2024-09-12T08:00:00Z',
  },
  {
    id: 'user-oliver',
    username: 'oliverchen',
    displayName: 'Oliver Chen',
    email: 'oliver@chen.design',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1558655146-d09347e92766?q=80&w=1200&auto=format&fit=crop',
    bio: 'Principal Product Designer. Building clean design systems, keyboard-first web tools, and thoughtful typography.',
    websiteUrl: 'https://oliverchen.me',
    location: 'San Francisco, CA',
    followersCount: 21300,
    followingCount: 195,
    postsCount: 24,
    collectionsCount: 8,
    profileViews: 24100,
    isAdmin: true,
    createdAt: '2024-08-01T12:00:00Z',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    creatorId: 'user-elena',
    creator: {
      id: 'user-elena',
      username: 'elenavance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Typographic Monograph — Vol. 04',
    description: 'Experimental typographic exhibition poster designed with high-contrast neo-grotesque type, dynamic column grids, and monochrome metallic foil overlays.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.72,
    category: 'posters',
    tags: ['Poster', 'Swiss Style', 'Typography', 'Monochrome', 'Editorial'],
    styleTags: ['Brutalist', 'Minimal', 'Swiss'],
    toolsUsed: ['InDesign', 'Illustrator', 'Glyphs'],
    sourceUrl: 'https://elenavance.design/projects/monograph-04',
    likesCount: 1420,
    savesCount: 890,
    viewsCount: 18400,
    uniqueImpressionsCount: 61200,
    impressionsBySource: { home: 36700, search: 14200, related: 7100, profile: 3200 },
    commentsCount: 38,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-28T14:00:00Z',
  },
  {
    id: 'post-2',
    creatorId: 'user-mono',
    creator: {
      id: 'user-mono',
      username: 'studiomono',
      displayName: 'Studio Mono',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Spatial Canvas UI & Command Palette',
    description: 'Clean dark-mode spatial interface featuring ambient backdrops, glassomorphic floating control chips, and seamless canvas navigation.',
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 1.25,
    category: 'ui-ux',
    tags: ['UI/UX', 'Design System', 'Dark Mode', 'Spatial UI', 'Figma'],
    styleTags: ['Futuristic', 'Clean', 'Modern'],
    toolsUsed: ['Figma', 'React', 'Tailwind'],
    sourceUrl: 'https://studiomono.io/spatial-canvas',
    likesCount: 2890,
    savesCount: 1740,
    viewsCount: 34200,
    uniqueImpressionsCount: 98500,
    impressionsBySource: { home: 58000, search: 24000, related: 11500, profile: 5000 },
    commentsCount: 92,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-25T11:20:00Z',
  },
  {
    id: 'post-3',
    creatorId: 'user-kaelen',
    creator: {
      id: 'user-kaelen',
      username: 'kaelen',
      displayName: 'Kaelen Rhee',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Chromatic Iridescence No. 8',
    description: 'Procedural 3D fluid simulations with dispersed prism reflections and subsurface scattering textures.',
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.8,
    category: '3d',
    tags: ['3D Render', 'Iridescent', 'Cinema4D', 'Octane', 'Fluid'],
    styleTags: ['Organic', 'Abstract', 'Vibrant'],
    toolsUsed: ['Cinema 4D', 'Octane Render', 'Houdini'],
    sourceUrl: 'https://kaelen.art/iridescence',
    likesCount: 3120,
    savesCount: 2210,
    viewsCount: 42100,
    uniqueImpressionsCount: 135000,
    impressionsBySource: { home: 82000, search: 31000, related: 16000, profile: 6000 },
    commentsCount: 64,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'post-4',
    creatorId: 'user-sofia',
    creator: {
      id: 'user-sofia',
      username: 'sofiarostova',
      displayName: 'Sofia Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Brutalist Geometry in Mediterranean Light',
    description: 'Shadow study capturing warm natural raking sunlight cutting across raw cast concrete stairs in Valencia.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.75,
    category: 'photography',
    tags: ['Architecture', 'Minimalism', 'Shadows', 'Concrete', 'Light'],
    styleTags: ['Warm', 'Minimal', 'Geometric'],
    toolsUsed: ['Leica M11', 'Lightroom'],
    sourceUrl: 'https://sofiarostova.photo/valencia-concrete',
    likesCount: 1840,
    savesCount: 1120,
    viewsCount: 21900,
    uniqueImpressionsCount: 74800,
    impressionsBySource: { home: 44000, search: 18000, related: 9200, profile: 3600 },
    commentsCount: 29,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-08-20T16:40:00Z',
  },
  {
    id: 'post-5',
    creatorId: 'user-elena',
    creator: {
      id: 'user-elena',
      username: 'elenavance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Aura Botanical Skin Care Packaging',
    description: 'Eco-conscious tactile amber glass cosmetic packaging featuring blind debossed textured cotton labels and custom serif logotype.',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.85,
    category: 'packaging',
    tags: ['Packaging', 'Cosmetics', 'Sustainable', 'Branding', 'Embossed'],
    styleTags: ['Tactile', 'Organic', 'Refined'],
    toolsUsed: ['Illustrator', 'Dimension', 'Photoshop'],
    sourceUrl: 'https://elenavance.design/projects/aura-botanicals',
    likesCount: 2100,
    savesCount: 1530,
    viewsCount: 29100,
    uniqueImpressionsCount: 88400,
    impressionsBySource: { home: 51000, search: 22000, related: 11000, profile: 4400 },
    commentsCount: 45,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-18T13:10:00Z',
  },
  {
    id: 'post-6',
    creatorId: 'user-oliver',
    creator: {
      id: 'user-oliver',
      username: 'oliverchen',
      displayName: 'Oliver Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Kinetic Web Editorial for Architecture Biennial',
    description: 'High-speed editorial landing page exploring modular grid layouts, asymmetric typographic hierarchy, and responsive fluid type curves.',
    imageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 1.35,
    category: 'website-design',
    tags: ['Web Design', 'Editorial', 'Typography', 'Landing Page', 'Motion'],
    styleTags: ['Editorial', 'Modern', 'Grid'],
    toolsUsed: ['Figma', 'Next.js', 'Tailwind CSS'],
    sourceUrl: 'https://oliverchen.me/work/biennial-editorial',
    likesCount: 1680,
    savesCount: 970,
    viewsCount: 19800,
    uniqueImpressionsCount: 65200,
    impressionsBySource: { home: 38000, search: 16000, related: 8200, profile: 3000 },
    commentsCount: 28,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-08-16T18:00:00Z',
  },
  {
    id: 'post-7',
    creatorId: 'user-mono',
    creator: {
      id: 'user-mono',
      username: 'studiomono',
      displayName: 'Studio Mono',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Voxel Brand Identity & Visual System',
    description: 'Modular geometric branding identity system created for an autonomous robotics collective. Features dynamic logotypes and generative stationery.',
    imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.8,
    category: 'branding',
    tags: ['Branding', 'Identity', 'Visual System', 'Stationery', 'Geometric'],
    styleTags: ['Tech', 'Geometric', 'Systematic'],
    toolsUsed: ['Illustrator', 'Figma', 'Processing'],
    sourceUrl: 'https://studiomono.io/voxel-identity',
    likesCount: 2450,
    savesCount: 1620,
    viewsCount: 31500,
    uniqueImpressionsCount: 94200,
    impressionsBySource: { home: 54000, search: 25000, related: 10500, profile: 4700 },
    commentsCount: 52,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'post-8',
    creatorId: 'user-kaelen',
    creator: {
      id: 'user-kaelen',
      username: 'kaelen',
      displayName: 'Kaelen Rhee',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Generative Latent Flora — Synthetic Botany',
    description: 'Generative visual exploration blending algorithmic neural diffusion models with physical microscope crystal formations.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.75,
    category: 'ai-art',
    tags: ['AI Art', 'Generative', 'Latent Space', 'Botanical', 'Abstract'],
    styleTags: ['Surreal', 'Generative', 'Organic'],
    toolsUsed: ['Midjourney', 'Photoshop', 'ComfyUI'],
    sourceUrl: 'https://kaelen.art/synthetic-botany',
    likesCount: 3490,
    savesCount: 2600,
    viewsCount: 48900,
    uniqueImpressionsCount: 152000,
    impressionsBySource: { home: 91000, search: 38000, related: 17000, profile: 6000 },
    commentsCount: 88,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-12T15:30:00Z',
  },
  {
    id: 'post-9',
    creatorId: 'user-oliver',
    creator: {
      id: 'user-oliver',
      username: 'oliverchen',
      displayName: 'Oliver Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Kanso Daily Focus & Task Companion',
    description: 'Minimalist iOS productivity app featuring gestural kanban columns, dynamic island widget states, and monochrome typography.',
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.7,
    category: 'mobile-app-design',
    tags: ['Mobile App', 'iOS', 'UI Design', 'Minimalism', 'Productivity'],
    styleTags: ['Minimal', 'Clean', 'Tactile'],
    toolsUsed: ['Figma', 'SwiftUI'],
    sourceUrl: 'https://oliverchen.me/kanso-app',
    likesCount: 2780,
    savesCount: 1890,
    viewsCount: 36700,
    uniqueImpressionsCount: 112000,
    impressionsBySource: { home: 67000, search: 28000, related: 12500, profile: 4500 },
    commentsCount: 62,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-10T11:45:00Z',
  },
  {
    id: 'post-10',
    creatorId: 'user-sofia',
    creator: {
      id: 'user-sofia',
      username: 'sofiarostova',
      displayName: 'Sofia Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Nordic Gallery Monogram & Identity Mark',
    description: 'Subtle geometric monogram crafted for a contemporary photography museum in Oslo. Rooted in optical balance and negative space.',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 1.0,
    category: 'logos',
    tags: ['Logo', 'Monogram', 'Minimal', 'Vector', 'Negative Space'],
    styleTags: ['Minimal', 'Geometric', 'Timeless'],
    toolsUsed: ['Illustrator', 'Glyphs'],
    sourceUrl: 'https://sofiarostova.photo/nordic-gallery',
    likesCount: 1530,
    savesCount: 920,
    viewsCount: 17600,
    uniqueImpressionsCount: 58400,
    impressionsBySource: { home: 34000, search: 15000, related: 6800, profile: 2600 },
    commentsCount: 24,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-08-08T09:20:00Z',
  },
  {
    id: 'post-11',
    creatorId: 'user-elena',
    creator: {
      id: 'user-elena',
      username: 'elenavance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Risograph Print Anthology — Tokyo Sessions',
    description: 'Dual-tone fluorescent orange and teal risograph prints produced during a printmaking residency in Nakameguro.',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 0.78,
    category: 'illustration',
    tags: ['Illustration', 'Risograph', 'Print', 'Duo-Tone', 'Tokyo'],
    styleTags: ['Tactile', 'Vintage', 'Artistic'],
    toolsUsed: ['Procreate', 'Risograph Machine', 'Photoshop'],
    sourceUrl: 'https://elenavance.design/projects/tokyo-riso',
    likesCount: 2240,
    savesCount: 1410,
    viewsCount: 26800,
    uniqueImpressionsCount: 84600,
    impressionsBySource: { home: 49000, search: 21000, related: 10600, profile: 4000 },
    commentsCount: 41,
    isPublished: true,
    isFeatured: true,
    createdAt: '2026-08-06T14:15:00Z',
  },
  {
    id: 'post-12',
    creatorId: 'user-mono',
    creator: {
      id: 'user-mono',
      username: 'studiomono',
      displayName: 'Studio Mono',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    },
    title: 'Ephemeral Brand Launch Campaign Carousel',
    description: 'Structured 10-slide Instagram carousel design featuring bold typography headlines, staggered motion mockups, and micro-branding accents.',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1000&auto=format&fit=crop',
    aspectRatio: 1.0,
    category: 'social-media-design',
    tags: ['Social Media', 'Carousel', 'Instagram', 'Marketing', 'Typography'],
    styleTags: ['Dynamic', 'High-Contrast', 'Modern'],
    toolsUsed: ['Figma', 'After Effects'],
    sourceUrl: 'https://studiomono.io/ephemeral-launch',
    likesCount: 1390,
    savesCount: 880,
    viewsCount: 15400,
    uniqueImpressionsCount: 52100,
    impressionsBySource: { home: 30000, search: 13500, related: 6200, profile: 2400 },
    commentsCount: 22,
    isPublished: true,
    isFeatured: false,
    createdAt: '2026-08-04T16:00:00Z',
  },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    userId: 'user-oliver',
    title: 'Brutalist Posters & Typography',
    description: 'Posters with Swiss grid discipline, oversized letters, and raw contrast.',
    isPrivate: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=600&auto=format&fit=crop',
    postIds: ['post-1', 'post-6', 'post-11'],
    postsCount: 3,
    createdAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'col-2',
    userId: 'user-oliver',
    title: 'Clean Minimal UI & Design Tokens',
    description: 'Inspirational digital product interfaces, micro-interactions, and command bars.',
    isPrivate: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=600&auto=format&fit=crop',
    postIds: ['post-2', 'post-9'],
    postsCount: 2,
    createdAt: '2026-08-12T14:30:00Z',
  },
  {
    id: 'col-3',
    userId: 'user-oliver',
    title: 'Tactile Shaders & 3D Lighting',
    description: 'Procedural textures, glass refraction studies, and octane lighting experiments.',
    isPrivate: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=600&auto=format&fit=crop',
    postIds: ['post-3', 'post-8'],
    postsCount: 2,
    createdAt: '2026-08-15T09:10:00Z',
  },
  {
    id: 'col-4',
    userId: 'user-elena',
    title: 'Packaging & Print Crafts',
    description: 'Tactile materials, embossing, and sustainable branding artifacts.',
    isPrivate: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=600&auto=format&fit=crop',
    postIds: ['post-5', 'post-7', 'post-10'],
    postsCount: 3,
    createdAt: '2026-08-18T10:00:00Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    postId: 'post-1',
    userId: 'user-mono',
    user: {
      id: 'user-mono',
      username: 'studiomono',
      displayName: 'Studio Mono',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    },
    content: 'The optical kerning on that display headline is immaculate. Did you draw custom glyphs for the ligature?',
    createdAt: '2026-08-28T15:30:00Z',
  },
  {
    id: 'comment-2',
    postId: 'post-1',
    userId: 'user-oliver',
    user: {
      id: 'user-oliver',
      username: 'oliverchen',
      displayName: 'Oliver Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    },
    content: 'Saved to my Brutalist Posters collection. The metallic foil texture brings so much depth to the piece.',
    createdAt: '2026-08-28T16:12:00Z',
  },
  {
    id: 'comment-3',
    postId: 'post-2',
    userId: 'user-kaelen',
    user: {
      id: 'user-kaelen',
      username: 'kaelen',
      displayName: 'Kaelen Rhee',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    },
    content: 'This glass depth aesthetic feels so tactile. Super inspiring work!',
    createdAt: '2026-08-25T13:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-welcome',
    userId: 'user-oliver',
    type: 'system',
    title: 'Welcome to KROMA',
    message: 'Your space for remarkable visual work is ready. Explore ideas, save what inspires you, and start shaping a collection that feels like yours.',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-post-elena',
    userId: 'user-oliver',
    type: 'post',
    title: 'Elena Vance published new work',
    message: 'Typographic Monograph — Vol. 04 is now live in Posters.',
    actor: {
      id: 'user-elena',
      username: 'elenavance',
      displayName: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    },
    targetPost: {
      id: 'post-1',
      title: 'Typographic Monograph — Vol. 04',
      imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    },
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'notif-save-kaelen',
    userId: 'user-oliver',
    type: 'save',
    title: 'Kaelen Rhee saved your visual',
    message: 'Saved "Kanso Daily Focus & Task Companion" to Clean Minimal UI & Design Tokens.',
    actor: {
      id: 'user-kaelen',
      username: 'kaelen',
      displayName: 'Kaelen Rhee',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop',
    },
    targetPost: {
      id: 'post-9',
      title: 'Kanso Daily Focus & Task Companion',
      imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1000&auto=format&fit=crop',
    },
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
];

